import { expect, test } from "bun:test";
import { chromium } from "playwright-core";
import { mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createRequire } from "node:module";
import type * as Host from "../launcher/diagnostics/host";
import type { DiagnosticEvent } from "../src/diagnostics/contracts";

// Real React, Chromium clipboard, emitted host, worker, SQLite, report files. HTTP replaces Electron IPC;
// the native chooser is a deterministic test-owned destination. No account, runtime channel, or model is used.
test("diagnostics controls preserve scoped evidence, stable layout, clipboard contents, and persisted deletion", async () => {
  const root = mkdtempSync(join(tmpdir(), "diagnostics-acceptance-"));
  const host = createRequire(import.meta.url)(resolve("launcher/electron/generated/diagnostics.cjs")) as typeof Host;
  const logger = host.createLogger({ filePath: join(root, "launcher.jsonl"), invocation: { executable: process.execPath, args: [resolve("src/cli.ts"), "--home", root, "diagnostics", "worker"] }, environment: "test" });
  const browser = await chromium.launch({ executablePath: process.env.CHATGPT_TEST_CHROME_EXECUTABLE, headless: true });
  let server: ReturnType<typeof Bun.serve> | undefined;
  const output = join(root, "selection.json");
  let chooser: "save" | "cancel" | "fail" = "save", copied = "";
  const requests: Record<string, number> = {};
  const handlers = new Map<string, (event: unknown, ...args: unknown[]) => unknown>();
  try {
    await logger.ready;
    const start = Date.now();
    const events: DiagnosticEvent[] = [];
    for (let index = 1; index <= 125; index++) {
      const traceId = index.toString(16).padStart(32, "0");
      const rootSpan: DiagnosticEvent = { version: 1, id: crypto.randomUUID(), time: start + index, kind: "span", name: `fixture.operation.${index}`, body: `Recorded operation ${index}`, severity: "error", component: "launcher", environment: "test", target: "fixture", traceId, spanId: "a".repeat(16), attributes: { "service.version": "fixture" }, span: { startTime: start + index, endTime: start + index + 10, outcome: "cancelled" } };
      events.push(rootSpan, { ...rootSpan, id: crypto.randomUUID(), kind: "problem", span: undefined, name: "fixture_failure", problem: { version: 1, code: "fixture_failure", stage: "fixture", message: "Synthetic historical problem", actions: [], findings: [], causes: [], recovery: "unknown" } });
      if (index === 125) {
        events.push({ ...rootSpan, id: crypto.randomUUID(), time: start + 200, span: { startTime: start + index, outcome: "running" } });
        for (let depth = 1; depth <= 3; depth++) events.push({ ...rootSpan, id: crypto.randomUUID(), name: `fixture.child.${depth}`, severity: "info", spanId: String.fromCharCode(97 + depth).repeat(16), parentSpanId: String.fromCharCode(96 + depth).repeat(16), span: { startTime: start + index + depth, endTime: start + index + depth + 1, outcome: "succeeded" } });
      }
    }
    for (const event of events) logger.diagnostics.ingest(event);
    await logger.client!.flush();
    host.registerDiagnosticsIpc({ handle: (channel, handler) => { handlers.set(channel, handler); }, logger, copyText: text => { copied = text; }, chooseExport: async () => chooser === "cancel" ? undefined : chooser === "fail" ? join(root, "diagnostics", "observability", "forbidden.json") : output });
    const built = Bun.spawnSync([process.execPath, "build", "tests/fixtures/diagnostics-acceptance.tsx", "--target", "browser", "--outdir", root], { cwd: resolve("launcher") });
    expect(built.exitCode).toBe(0);
    server = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) {
      const url = new URL(request.url);
      if (url.pathname === "/rpc") {
        const { method, args } = await request.json() as { method: string; args: unknown[] };
        requests[method] = (requests[method] ?? 0) + 1;
        const result = await handlers.get(`launcher:diagnostics-${method}`)!({ sender: { id: 1 } }, ...args);
        return Response.json(method === "copy" ? { text: copied, metadata: result } : result ?? null);
      }
      if (url.pathname === "/app.js") return new Response(readFileSync(join(root, "diagnostics-acceptance.js")), { headers: { "content-type": "text/javascript" } });
      if (url.pathname === "/app.css") return new Response(readFileSync(join(root, "diagnostics-acceptance.css")), { headers: { "content-type": "text/css" } });
      return new Response('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><div id="root"></div><script type="module" src="/app.js"></script>', { headers: { "content-type": "text/html" } });
    } });
    const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, permissions: ["clipboard-read", "clipboard-write"], reducedMotion: "reduce", timezoneId: "UTC" });
    const page = await context.newPage(); page.setDefaultTimeout(8000);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
    page.on("requestfailed", request => errors.push(`Request failed: ${new URL(request.url()).pathname}`));
    try {
      await page.goto(`http://127.0.0.1:${server.port}`);
      await page.getByText(/125 Occurrences/).waitFor();
      // The empty inspector and its adjacent result card share the same visible card geometry.
      const resultCard = page.locator(".diagnostic-group > .diagnostic-record").first();
      const emptyInspector = page.getByRole("complementary", { name: "Operation details" });
      const cardBounds = await resultCard.boundingBox(), emptyBounds = await emptyInspector.boundingBox();
      expect(cardBounds).not.toBeNull(); expect(emptyBounds).not.toBeNull();
      expect(Math.abs(cardBounds!.y - emptyBounds!.y)).toBeLessThanOrEqual(1);
      expect(Math.abs(cardBounds!.height - emptyBounds!.height)).toBeLessThanOrEqual(2);
      expect(await emptyInspector.evaluate(element => getComputedStyle(element).paddingLeft)).toBe(await resultCard.evaluate(element => getComputedStyle(element).paddingLeft));
      expect(await emptyInspector.locator(".diagnostic-empty").evaluate(element => getComputedStyle(element).paddingTop)).toBe("0px");
      await page.getByRole("button", { name: "Occurrences", exact: true }).click();
      await page.getByRole("button", { name: "Load more", exact: true }).click();
      await page.getByRole("button", { name: "Operations", exact: true }).click();
      await page.getByRole("button", { name: /fixture operation 125/ }).click();
      await page.getByRole("heading", { name: "Stage timeline" }).waitFor();
      expect(await page.getByRole("complementary", { name: "Operation details" }).locator(":scope > h2").evaluate(element => getComputedStyle(element).marginTop)).toBe("0px");
      await page.getByText(/Recorded evidence conflicts/).waitFor();
      await page.getByRole("button", { name: /fixture child 3/ }).waitFor();
      const markers = await page.locator(".diagnostic-timeline li").evaluateAll(items => items.map(item => item.getBoundingClientRect().left + Number.parseFloat(getComputedStyle(item, "::before").left)));
      expect(new Set(markers).size).toBe(1);
      expect(await page.locator('.diagnostic-timeline li[data-depth="3"]').count()).toBe(1);
      expect(await page.locator('.diagnostic-timeline li[data-outcome="running"]').count()).toBe(0);
      const copyTrigger = page.getByRole("button", { name: "Copy", exact: true });
      await copyTrigger.click();
      const menu = page.getByRole("menu", { name: "Copy", exact: true });
      await menu.waitFor();
      const anchor = await copyTrigger.boundingBox(), bounds = await menu.boundingBox();
      expect(anchor).not.toBeNull(); expect(bounds).not.toBeNull();
      expect(bounds!.y).toBeGreaterThanOrEqual(anchor!.y + anchor!.height);
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(1280);
      expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(900);
      await page.keyboard.press("End");
      expect(await page.getByRole("menuitem", { name: "Structured JSON", exact: true }).evaluate(element => element === document.activeElement)).toBe(true);
      await page.keyboard.press("Escape");
      expect(await copyTrigger.evaluate(element => element === document.activeElement)).toBe(true);
      expect(await menu.count()).toBe(0);
      const report = async (action: "Copy" | "Export", scope: string, format: string) => {
        await page.getByRole("button", { name: action, exact: true }).click();
        await page.getByRole("menuitemradio", { name: scope, exact: true }).click();
        await page.getByRole("menuitem", { name: format, exact: true }).click();
      };
      await report("Copy", "This operation", "Structured JSON");
      await page.getByText(/6 records/).waitFor();
      const feedback = page.getByRole("region", { name: "Action feedback", exact: true });
      const initialFeedbackHeight = (await feedback.boundingBox())!.height;
      expect((await feedback.boundingBox())!.width).toBeLessThan(600);
      expect(await page.locator(".diagnostics-workspace").evaluate(element => element.getBoundingClientRect().bottom)).toBe(900);
      const clipboard = JSON.parse(await page.evaluate(() => navigator.clipboard.readText()));
      expect(clipboard.events).toHaveLength(6);
      expect(new Set(clipboard.events.map((event: DiagnosticEvent) => event.traceId)).size).toBe(1);
      await report("Copy", "This event", "Structured JSON");
      await page.getByText("1 records", { exact: true }).waitFor();
      expect(JSON.parse(await page.evaluate(() => navigator.clipboard.readText())).events).toHaveLength(1);
      await report("Export", "Current results", "Structured JSON");
      await page.getByText(output, { exact: false }).waitFor();
      expect(JSON.parse(readFileSync(output, "utf8")).events).toHaveLength(125);
      chooser = "cancel";
      await report("Export", "All retained diagnostics", "Support bundle");
      await page.locator('.launcher-action-feedback [data-status="cancelled"]').waitFor();
      chooser = "fail";
      await report("Export", "All retained diagnostics", "Structured JSON");
      await page.locator('.launcher-action-feedback [data-status="failed"]').waitFor();
      expect((await feedback.boundingBox())!.height).toBe(initialFeedbackHeight);
      await feedback.getByRole("button", { name: /Details/ }).click();
      await feedback.getByRole("button", { name: "Open Diagnostics", exact: true }).waitFor();
      expect((await feedback.boundingBox())!.height).toBe(initialFeedbackHeight);
      await page.keyboard.press("Escape");
      expect(await feedback.getByRole("button", { name: /Details/ }).evaluate(element => element === document.activeElement)).toBe(true);
      expect(existsSync(join(root, "diagnostics", "observability", "forbidden.json"))).toBe(false);
      await page.getByRole("button", { name: "Advanced", exact: true }).click();
      await page.getByRole("combobox", { name: "Search mode" }).selectOption("regex");
      await page.getByRole("searchbox", { name: "Search events" }).fill("[");
      await page.getByText("Enter a valid regular expression.", { exact: true }).waitFor();
      await page.getByRole("searchbox", { name: "Search events" }).fill("fixture");
      await page.getByLabel("Trace ID", { exact: true }).fill("bad");
      await page.getByText(/Enter a nonzero 32-character/).waitFor();
      await copyTrigger.click();
      await page.getByRole("menuitemradio", { name: "Current results", exact: true }).click();
      const invalidCopy = page.getByRole("menuitem", { name: "Structured JSON", exact: true });
      expect(await invalidCopy.isDisabled()).toBe(true);
      expect(await invalidCopy.getAttribute("title")).toContain("trace ID");
      await page.keyboard.press("Escape");
      await page.getByLabel("Trace ID", { exact: true }).fill("");
      await page.getByLabel("From", { exact: true }).fill("2026-09-06T00:00");
      await page.getByLabel("To", { exact: true }).fill("2026-09-05T00:00");
      await page.getByText(/Enter valid dates/).waitFor();
      await page.getByLabel("From", { exact: true }).fill(""); await page.getByLabel("To", { exact: true }).fill("");
      await page.getByRole("combobox", { name: "Search mode", exact: true }).selectOption("text");
      await page.getByRole("searchbox", { name: "Search events" }).fill("");
      await page.getByRole("combobox", { name: "Component", exact: true }).selectOption("launcher");
      await page.getByRole("combobox", { name: "Target", exact: true }).selectOption("fixture");
      await page.getByRole("combobox", { name: "Severity", exact: true }).selectOption("warning");
      await page.getByText("No records match this view.", { exact: true }).waitFor();
      await page.getByRole("combobox", { name: "Severity", exact: true }).selectOption("error");
      await page.getByRole("listitem").first().waitFor();
      await page.getByLabel("Task ID", { exact: true }).fill("absent-fixture-task");
      await page.getByText("No records match this view.", { exact: true }).waitFor();
      await page.getByLabel("Task ID", { exact: true }).fill("");
      await page.getByRole("listitem").first().waitFor();
      await page.getByRole("button", { name: "Pause updates", exact: true }).click();
      await page.getByRole("button", { name: "Refresh", exact: true }).click();
      await page.getByRole("button", { name: "Resume updates", exact: true }).click();
      await page.getByRole("button", { name: "Capture & storage", exact: true }).click();
      await page.getByRole("button", { name: "Enable debug for 30 minutes" }).click();
      await page.getByRole("button", { name: "Stop debug", exact: true }).waitFor();
      expect((await logger.client!.status()).captures.debugUntil).toBeGreaterThan(Date.now());
      expect(await page.getByRole("button", { name: "Start scoped capture", exact: true }).isDisabled()).toBe(true);
      await page.getByRole("checkbox", { name: /I understand screenshots/ }).check();
      await page.getByRole("button", { name: "Start scoped capture", exact: true }).click();
      await page.getByRole("button", { name: "Stop private capture", exact: true }).last().waitFor();
      expect(await logger.client!.claimCapture("f".repeat(32))).toBe(false);
      const selectedTrace = (125).toString(16).padStart(32, "0");
      expect(await logger.client!.claimCapture(selectedTrace)).toBe(true);
      await logger.client!.writeCapture(selectedTrace, Buffer.from([137,80,78,71,13,10,26,10,0]));
      await page.getByRole("button", { name: "Stop private capture", exact: true }).last().click();
      await page.getByRole("button", { name: "Start scoped capture", exact: true }).waitFor();
      expect((await logger.client!.status()).captures.privateUntil).toBe(0);
      expect((await logger.client!.status()).privateBytes).toBeGreaterThan(0);
      await page.getByRole("button", { name: "Delete private captures", exact: true }).click();
      await page.getByRole("button", { name: "Delete records", exact: true }).click();
      await page.locator('.launcher-action-feedback [data-status="succeeded"]').first().waitFor();
      await page.waitForFunction(() => !document.querySelector("dialog[open]"));
      // Independent worker read is the persisted deletion oracle, not the notification.
      expect((await logger.client!.status()).privateBytes).toBe(0);
      await page.getByRole("button", { name: "Stop debug", exact: true }).click();
      await page.getByRole("button", { name: "Enable debug for 30 minutes", exact: true }).waitFor();
      await page.locator('.capture-indicator').waitFor({ state: "hidden" });
      expect((await logger.client!.status()).captures.debugUntil).toBe(0);
      await page.getByRole("button", { name: "Clear normal diagnostics", exact: true }).click();
      await page.keyboard.press("Escape");
      expect((await logger.client!.status()).eventCount).toBeGreaterThan(0);
      await page.getByRole("button", { name: "Clear normal diagnostics", exact: true }).click();
      await page.getByRole("button", { name: "Delete records", exact: true }).click();
      await page.getByRole("button", { name: "Refresh", exact: true }).click();
      expect((await logger.client!.status()).eventCount).toBe(0);
      expect(errors).toEqual([]);
    } catch (error) {
      const artifact = resolve("context/diagnostics-acceptance-failure.png");
      await page.screenshot({ path: artifact, fullPage: true });
      const feedback = page.locator('.launcher-action-feedback');
      throw new Error(`${String(error)}\nSynthetic UI: ${(await page.locator("body").innerText()).slice(0, 4000)}\nFeedback: ${await feedback.count() ? await feedback.innerText() : "No feedback"}\nRequests: ${JSON.stringify(requests)}\nExport exists: ${existsSync(output)}\nErrors: ${JSON.stringify(errors)}\nScreenshot: ${artifact}`);
    } finally { await context.close(); }
  } finally { await browser.close(); server?.stop(true); await logger.close(); rmSync(root, { recursive: true, force: true }); }
}, 90000);
